DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE BOOKS
(
    ID        BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID BIGINT,
    GENRE_ID  BIGINT,
    NAME      VARCHAR(255)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID      BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR(255),
    SURNAME VARCHAR(255)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID    BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    GENRE VARCHAR(255)
);

ALTER TABLE BOOKS
    ADD CONSTRAINT FK_BOOKS_ON_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID);
ALTER TABLE BOOKS
    ADD CONSTRAINT FK_BOOKS_ON_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID);